# Generated by Django 2.2.4 on 2019-08-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phyloGenie', '0002_recommendations'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreprocessModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_clean_time', models.CharField(max_length=100000)),
                ('alignment_time', models.CharField(max_length=100000)),
            ],
        ),
    ]
