# Generated by Django 2.2.4 on 2019-09-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phyloGenie', '0003_auto_20190918_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='data',
            field=models.FileField(upload_to=''),
        ),
    ]
