# Generated by Django 2.2.4 on 2019-09-21 07:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phyloGenie', '0005_dataset_tree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='sim_score',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=7),
        ),
    ]
